version: '3.8'
services:
  student-crud:
    build: ./student-crud
    container_name: student-crud-backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/docker-demo-db
      SPRING_DATASOURCE_USERNAME: lucky
      SPRING_DATASOURCE_PASSWORD: papa
    depends_on:
      postgresdb:
        condition: service_healthy

  student-react:
    build: ./student-react-project
    container_name: student-react-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - student-crud


  postgresdb:
    image: postgres:16
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: docker-demo-db
      POSTGRES_USER: lucky
      POSTGRES_PASSWORD: papa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lucky -d docker-demo-db"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  pgdata:
